language: perl

install:
  - git clone https://github.com/Perl5-Alien/Alien-Base.git
  - cd Alien-Base
  - cpanm . -v
  - cd ..
  - rm -rf Alien-Base
  - git clone https://github.com/Perl5-Alien/Alien-Base-Extras.git
  - tar xf Alien-Base-Extras/Acme-Alien-DontPanic/inc/dontpanic-1.0.tar.gz
  - cd dontpanic-1.0
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - rm -rf dontpanic-1.0
  - cd Alien-Base-Extras/Acme-Alien-DontPanic
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install
  - cd ../..
  - cpanm -n https://dist.wdlabs.com/FFI-Platypus-0.08.tar.gz

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
