name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cip:
          - tag: "static"
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.33"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.33"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.32"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.32"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.30"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.30"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.28"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.28"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.26"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.26"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.24"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.24"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.22"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.22"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.20"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.20"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.18"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.18"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.16"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.16"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.14"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.14"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.12"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.12"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.10"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.10"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=share"
            tag: "5.8"
            tmpdir: /home/cip/tmp
          - env: "ALIEN_INSTALL_TYPE=system"
            tag: "5.8"
            tmpdir: /home/cip/tmp

    env:
      CIP_ENV: ${{ matrix.cip.env }}
      CIP_TAG: ${{ matrix.cip.tag }}
      TMPDIR: ${{ matrix.cip.tmpdir }}


    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap CIP
        run: |
          curl -L https://raw.githubusercontent.com/uperl/cip/main/bin/github-bootstrap | bash

      - name: Cache-Key
        id: cache-key
        run: |
          echo -n '::set-output name=key::'
          cip cache-key

      - name: Cache CPAN modules
        uses: actions/cache@v2
        with:
          path: ~/.cip
          key: ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}

      - name: Start-Container
        run: |
          cip start

      - name: Diagnostics
        run: |
          cip diag

      - name: Install-Dependencies
        run: |
          cip install

      - name: Build + Test
        run: |
          cip script
